version: '3.1'
services:
  coredns:
    build: .
    container_name: coredns
    restart: unless-stopped
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - './config:/etc/coredns'
    networks:
      home:
        ipv4_address: 10.42.4.2
        aliases:
          - ns2.murderhaus.com
networks:
  home:
    external:
      name: home-segment
